name: Workflow_2 - Increase App Version oktets on pull request
on:
  pull_request_review:
    types: [submitted]
    branches:
      - master

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Get current version
      id: get_version
      run: |
        VERSION_FILE="src/MahjongCore/MahjongCore.csproj"
        VERSION_REGEX='<Version>([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9A-Fa-f]+)<\/Version>'
        if grep -qP "$VERSION_REGEX" "$VERSION_FILE"; then
          APP_VERSION=$(grep -oP "$VERSION_REGEX" "$VERSION_FILE" | sed -E "s/$VERSION_REGEX/\1.\2.\3.\4/")
          echo "Current version: $APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "VERSION_FILE=$VERSION_FILE" >> $GITHUB_ENV
        else
          echo "Version tag not found in $VERSION_FILE with regex $VERSION_REGEX"
          exit 1
        fi
      shell: bash

    - name: Increment version
      id: increment_version
      run: |
        APP_VERSION="${{ env.APP_VERSION }}"
        VERSION_FILE="${{ env.VERSION_FILE }}"
        echo "Current version from env: $APP_VERSION"
        IFS='.' read -r -a VERSION_PARTS <<< "$APP_VERSION"
        MAJOR=${VERSION_PARTS[0]}
        FEATURE=${VERSION_PARTS[1]}
        BUG=${VERSION_PARTS[2]}
        BUILD=${VERSION_PARTS[3]}

        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          if echo "$PR_TITLE" | grep -iq "\[major\]"; then
            MAJOR=$((MAJOR + 1))
            FEATURE=0
            BUG=0
          elif echo "$PR_TITLE" | grep -iq "\[feature\]"; then
            FEATURE=$((FEATURE + 1))
            BUG=0
          elif echo "$PR_TITLE" | grep -iq "\[bug\]"; then
            BUG=$((BUG + 1))
          fi
        fi

        INCREMENTED_APP_VERSION="$MAJOR.$FEATURE.$BUG.$BUILD"
        echo "INCREMENTED_APP_VERSION=$INCREMENTED_APP_VERSION" >> $GITHUB_ENV

        echo "New version: $INCREMENTED_APP_VERSION"

        if [[ "${{ env.APP_VERSION }}" == $INCREMENTED_APP_VERSION ]]; then
            exit 0
        fi
        
        if [[ -f "$VERSION_FILE" ]]; then
          echo "File $VERSION_FILE found. Attempting to update version."
          sed -i "s/<Version>$APP_VERSION<\/Version>/<Version>$INCREMENTED_APP_VERSION<\/Version>/" "$VERSION_FILE"
          echo "Version updated successfully."
        else
          echo "File $VERSION_FILE not found."
          exit 1
        fi

        echo "INCREMENTED_APP_VERSION=$INCREMENTED_APP_VERSION" >> $GITHUB_ENV
      shell: bash
      env:
        VERSION_FILE: ${{ env.VERSION_FILE }}
        APP_VERSION: ${{ env.APP_VERSION }}

    - name: Commit version increment
      run: |
        if [[ "${{ env.APP_VERSION }}" == "${{ env.INCREMENTED_APP_VERSION }}" ]]; then
            exit 0
        fi

        git config --local user.name 'github-actions'
        git config --local user.email 'github-actions@github.com'
        git add "${{ env.VERSION_FILE }}"
        git commit -m "Incremented App Version from ${{ env.APP_VERSION }} to ${{ env.INCREMENTED_APP_VERSION }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
