name: Auto Increment Version

on:
  pull_request:
    types: [submitted]
  push:
    branches:
      - '**'

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Get current version
      id: get_version
      run: |
        VERSION_FILE="src/MahjongCore/MahjongCore.csproj"
        VERSION_REGEX='<Version>([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9A-Fa-f]+)<\/Version>'
        if grep -qP "$VERSION_REGEX" "$VERSION_FILE"; then
          CURRENT_VERSION=$(grep -oP "$VERSION_REGEX" "$VERSION_FILE" | sed -E "s/$VERSION_REGEX/\1.\2.\3.\4/")
          echo "Current version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "VERSION_FILE=$VERSION_FILE" >> $GITHUB_ENV
        else
          echo "Version tag not found in $VERSION_FILE with regex $VERSION_REGEX"
          exit 1
        fi
      shell: bash

    - name: Increment version
      id: increment_version
      run: |
        CURRENT_VERSION="${{ env.current_version }}"
        VERSION_FILE="${{ env.VERSION_FILE }}"
        COMMIT_SHA="${{ github.sha }}"
        echo "Current version from env: $CURRENT_VERSION"
        IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
        MAJOR=${VERSION_PARTS[0]}
        FEATURE=${VERSION_PARTS[1]}
        BUG=${VERSION_PARTS[2]}
        BUILD=${COMMIT_SHA:0:7}  # Use the first 7 characters of the commit SHA

        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          if echo "$PR_TITLE" | grep -iq "\[major\]"; then
            MAJOR=$((MAJOR + 1))
            FEATURE=0
            BUG=0
            BUILD=0
          elif echo "$PR_TITLE" | grep -iq "\[feature\]"; then
            FEATURE=$((FEATURE + 1))
            BUG=0
            BUILD=0
          elif echo "$PR_TITLE" | grep -iq "\[bug\]"; then
            BUG=$((BUG + 1))
            BUILD=0
          fi
        fi

        NEW_VERSION="$MAJOR.$FEATURE.$BUG.$BUILD"
        echo "New version: $NEW_VERSION"

        if [[ -f "$VERSION_FILE" ]]; then
          echo "File $VERSION_FILE found. Attempting to update version."
          sed -i "s/<Version>$CURRENT_VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" "$VERSION_FILE"
          echo "Version updated successfully."
        else
          echo "File $VERSION_FILE not found."
          exit 1
        fi

        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
      shell: bash
      env:
        VERSION_FILE: ${{ env.VERSION_FILE }}
        current_version: ${{ env.current_version }}

    - name: Commit version increment
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add "${{ env.VERSION_FILE }}"
        git commit -m "Increment version to ${{ env.new_version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
